=== LedgerHQ/ledger-asset-dapps/bsc/b2c.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "blockchainName": {
            "enum": [
                "bsc"
            ]
        },
        "chainId": {
            "enum": [
                56
            ]
        },
        "contracts": {
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-f0-9]{40}$",
                        "type": "string"
                    },
                    "contractName": {
                        "type": "string"
                    },
                    "screens": {
                        "additionalProperties": false,
                        "description": "Optional description (per selector) of the screen displayed on PSD, overriding the default screen",
                        "patternProperties": {
                            "^0x[a-f0-9]{8}$": {
                                "items": {
                                    "additionalProperties": true,
                                    "description": "Same format as vault_common.json",
                                    "type": "object"
                                },
                                "type": "array"
                            }
                        },
                        "type": "object"
                    },
                    "selectors": {
                        "additionalProperties": false,
                        "patternProperties": {
                            "^0x[a-f0-9]{8}$": {
                                "properties": {
                                    "erc20OfInterest": {
                                        "items": [
                                            {
                                                "type": "string"
                                            }
                                        ],
                                        "type": "array"
                                    },
                                    "method": {
                                        "type": "string"
                                    },
                                    "plugin": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "plugin"
                                ],
                                "type": "object"
                            }
                        },
                        "type": "object"
                    }
                },
                "required": [
                    "address",
                    "contractName",
                    "selectors"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "contracts",
        "name",
        "chainId"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/bsc/nested/b2c.json
{
    "blockchainName": "bsc",
    "chainId": 56,
    "contracts": [
        {
            "address": "0x9a065e500cdcd01c0a506b0eb1a8b060b0ce1379",
            "contractName": "NestedFactory",
            "selectors": {
                "0x51227094": {
                    "erc20OfInterest": [
                        "_batchedOrders.0.outputToken",
                        "_batchedOrders.0.orders.-1.token"
                    ],
                    "method": "processOutputOrders",
                    "plugin": "Nested"
                },
                "0x90e1aa69": {
                    "erc20OfInterest": [
                        "_batchedOrders.0.inputToken",
                        "_batchedOrders.0.orders.-1.token"
                    ],
                    "method": "processInputOrders",
                    "plugin": "Nested"
                },
                "0xa378534b": {
                    "erc20OfInterest": [
                        "_batchedOrders.0.inputToken",
                        "_batchedOrders.0.orders.-1.token"
                    ],
                    "method": "create",
                    "plugin": "Nested"
                },
                "0xbba9b10c": {
                    "erc20OfInterest": [
                        "_buyToken",
                        "_orders.0.token"
                    ],
                    "method": "destroy",
                    "plugin": "Nested"
                }
            }
        },
        {
            "address": "0x449d088c9f184af598fe72d26742a58a11c5200f",
            "contractName": "FeeSplitter",
            "selectors": {
                "0x6d9634b7": {
                    "erc20OfInterest": [
                        "_tokens.0",
                        "_tokens.-1"
                    ],
                    "method": "releaseTokens",
                    "plugin": "Nested"
                }
            }
        },
        {
            "address": "0x0fff7f99d2b32849848e31cb48090c5268e06f65",
            "contractName": "NestedNFT",
            "selectors": {
                "0x23b872dd": {
                    "erc20OfInterest": [],
                    "method": "transferFrom",
                    "plugin": "Nested"
                }
            }
        }
    ],
    "name": "Nested"
}

=== LedgerHQ/ledger-asset-dapps/bsc/dodo/b2c.json
{
    "blockchainName": "bsc",
    "chainId": 56,
    "contracts": [
        {
            "address": "0x8f8dd7db1bda5ed3da8c9daf3bfa471c12d58486",
            "contractName": "DODOV2Proxy02",
            "selectors": {
                "0x1e6d24c2": {
                    "erc20OfInterest": [
                        "fromToken"
                    ],
                    "method": "dodoSwapV2TokenToETH",
                    "plugin": "DODO"
                },
                "0x5028bb95": {
                    "erc20OfInterest": [
                        "toToken"
                    ],
                    "method": "dodoSwapV2ETHToToken",
                    "plugin": "DODO"
                },
                "0x54bacd13": {
                    "erc20OfInterest": [
                        "fromToken",
                        "toToken"
                    ],
                    "method": "externalSwap",
                    "plugin": "DODO"
                },
                "0xf87dc1b7": {
                    "erc20OfInterest": [
                        "fromToken",
                        "toToken"
                    ],
                    "method": "dodoSwapV2TokenToToken",
                    "plugin": "DODO"
                }
            }
        },
        {
            "address": "0x6b3d817814eabc984d51896b1015c0b89e9737ca",
            "contractName": "DODORouteProxy",
            "selectors": {
                "0x7617b389": {
                    "erc20OfInterest": [
                        "fromToken",
                        "toToken"
                    ],
                    "method": "mixSwap",
                    "plugin": "DODO"
                },
                "0x81791788": {
                    "erc20OfInterest": [
                        "midToken.0",
                        "midToken.3"
                    ],
                    "method": "dodoMutliSwap",
                    "plugin": "DODO"
                }
            }
        },
        {
            "address": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
            "contractName": "WETH9",
            "selectors": {
                "0x2e1a7d4d": {
                    "erc20OfInterest": [],
                    "method": "withdraw",
                    "plugin": "DODO"
                },
                "0xd0e30db0": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "DODO"
                }
            }
        }
    ],
    "name": "DODO"
}

=== LedgerHQ/ledger-asset-dapps/bsc/stader/b2c.json
{
    "blockchainName": "bsc",
    "chainId": 56,
    "contracts": [
        {
            "address": "0x7276241a669489e4bbb76f63d2a43bfe63080f2f",
            "contractName": "StakeManager",
            "selectors": {
                "0x745400c9": {
                    "erc20OfInterest": [],
                    "method": "requestWithdraw",
                    "plugin": "Staderlabs"
                },
                "0xb13acedd": {
                    "erc20OfInterest": [],
                    "method": "claimWithdraw",
                    "plugin": "Staderlabs"
                },
                "0xd0e30db0": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Staderlabs"
                }
            }
        }
    ],
    "name": "Staderlabs"
}

=== LedgerHQ/ledger-asset-dapps/bsc/stakekit/b2c.json
{
    "blockchainName": "bsc",
    "chainId": 56,
    "contracts": [
        {
            "address": "0x0000000000000000000000000000000000001004",
            "contractName": "TokenHub",
            "selectors": {
                "0xaa7415f5": {
                    "erc20OfInterest": [],
                    "method": "transferOut",
                    "plugin": "StakeKit"
                }
            }
        },
        {
            "address": "0x0000000000000000000000000000000000002002",
            "contractName": "StakeHub",
            "selectors": {
                "0x4d99dd16": {
                    "erc20OfInterest": [],
                    "method": "undelegate",
                    "plugin": "StakeKit"
                },
                "0x59491871": {
                    "erc20OfInterest": [],
                    "method": "redelegate",
                    "plugin": "StakeKit"
                },
                "0x982ef0a7": {
                    "erc20OfInterest": [],
                    "method": "delegate",
                    "plugin": "StakeKit"
                },
                "0xaad3ec96": {
                    "erc20OfInterest": [],
                    "method": "claim",
                    "plugin": "StakeKit"
                }
            }
        }
    ],
    "name": "StakeKit"
}

=== LedgerHQ/ledger-asset-dapps/bsc/uniswap/b2c.json
{
    "blockchainName": "bsc",
    "chainId": 56,
    "contracts": [
        {
            "address": "0x4dae2f939acf50408e13d58534ff8c2776d45265",
            "contractName": "UniversalRouter",
            "selectors": {
                "0x3593564c": {
                    "erc20OfInterest": [],
                    "method": "execute",
                    "plugin": "Uniswap"
                }
            }
        },
        {
            "address": "0x1906c1d672b88cd1b9ac7593301ca990f94eae07",
            "contractName": "UniversalRouter",
            "selectors": {
                "0x3593564c": {
                    "erc20OfInterest": [],
                    "method": "execute",
                    "plugin": "Uniswap"
                }
            }
        }
    ],
    "name": "Uniswap"
}
