=== LedgerHQ/ledger-asset-dapps/arbitrum/eip712.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "blockchainName": {
            "enum": [
                "arbitrum"
            ]
        },
        "chainId": {
            "enum": [
                421611
            ]
        },
        "contracts": {
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-z0-9]{40}$",
                        "type": "string"
                    },
                    "contractName": {
                        "type": "string"
                    },
                    "messages": {
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "mapper": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "fields": {
                                            "items": {
                                                "additionalProperties": false,
                                                "properties": {
                                                    "label": {
                                                        "type": "string"
                                                    },
                                                    "path": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "path",
                                                    "label"
                                                ],
                                                "type": "object"
                                            },
                                            "type": "array"
                                        },
                                        "label": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "label",
                                        "fields"
                                    ],
                                    "type": "object"
                                },
                                "schema": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "schema",
                                "mapper"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "address",
                    "contractName",
                    "messages"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "contracts",
        "name",
        "chainId"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/arbitrum/tally/eip712.json
{
    "blockchainName": "arbitrum",
    "chainId": 421611,
    "contracts": [
        {
            "address": "0xf07ded9dc292157749b6fd268e37df6ea38395b9",
            "contractName": "L2ArbitrumGovernor",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Proposal id",
                                "path": "proposalId"
                            },
                            {
                                "label": "Support",
                                "path": "support"
                            }
                        ],
                        "label": "Arbitrum Foundation: Core Governor"
                    },
                    "schema": {
                        "Ballot": [
                            {
                                "name": "proposalId",
                                "type": "uint256"
                            },
                            {
                                "name": "support",
                                "type": "uint8"
                            }
                        ],
                        "EIP712Domain": [
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "address": "0x789fc99093b09ad01c34dc7251d0c89ce743e5a4",
            "contractName": "L2ArbitrumGovernor",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Proposal id",
                                "path": "proposalId"
                            },
                            {
                                "label": "Support",
                                "path": "support"
                            }
                        ],
                        "label": "Arbitrum Foundation: Treasury Governor"
                    },
                    "schema": {
                        "Ballot": [
                            {
                                "name": "proposalId",
                                "type": "uint256"
                            },
                            {
                                "name": "support",
                                "type": "uint8"
                            }
                        ],
                        "EIP712Domain": [
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "address": "0x912ce59144191c1204e64559fe8253a0e49e6548",
            "contractName": "Arbitrum",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Delegatee",
                                "path": "delegatee"
                            },
                            {
                                "label": "Nonce",
                                "path": "nonce"
                            },
                            {
                                "label": "Expiry",
                                "path": "expiry"
                            }
                        ],
                        "label": "ARB token"
                    },
                    "schema": {
                        "Delegation": [
                            {
                                "name": "delegatee",
                                "type": "address"
                            },
                            {
                                "name": "nonce",
                                "type": "uint256"
                            },
                            {
                                "name": "expiry",
                                "type": "uint256"
                            }
                        ],
                        "EIP712Domain": [
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "Tally"
}
