=== LedgerHQ/ledger-asset-dapps/ethereum/parsers.schema.json
{
    "$defs": {
        "argumentValue": {
            "additionalProperties": false,
            "properties": {
                "constant": {
                    "description": "A constant value, independant of the contract data to parse. Can be used to handle implicit tokens definitions.",
                    "type": "string"
                },
                "oneOf": [
                    {
                        "required": [
                            "path"
                        ]
                    },
                    {
                        "required": [
                            "constant"
                        ]
                    }
                ],
                "path": {
                    "additionalProperties": false,
                    "anyOf": [
                        {
                            "required": [
                                "default"
                            ]
                        },
                        {
                            "required": [
                                "transaction"
                            ]
                        },
                        {
                            "required": [
                                "default",
                                "transaction"
                            ]
                        }
                    ],
                    "description": "Defines the paths to use to extract the argument's value, either in the contract data or in the transaction data.",
                    "properties": {
                        "default": {
                            "type": "string"
                        },
                        "transaction": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "description": "Description of a DApp and all the contracts linked to it.",
    "properties": {
        "blockchainName": {
            "enum": [
                "ethereum"
            ]
        },
        "chainId": {
            "enum": [
                1
            ]
        },
        "contracts": {
            "additionalProperties": false,
            "description": "The different contracts linked to the over-arching DApp.",
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-fA-F0-9]{40}$",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "parsers": {
                        "description": "Description of contract's functions along with the arguments we want to parse and validate.",
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "arguments": {
                                    "description": "Arguments that we want to display on the device for user validation.",
                                    "items": {
                                        "properties": {
                                            "format": {
                                                "description": "The format (different from the type) describes how the parsed argument should be displayed on the device.",
                                                "enum": [
                                                    "amount",
                                                    "ascii",
                                                    "boolean",
                                                    "eip55",
                                                    "percentage",
                                                    "raw"
                                                ]
                                            },
                                            "name": {
                                                "description": "Internal name of the argument, can be different from the name in the ABI.",
                                                "type": "string"
                                            },
                                            "value": {
                                                "additionalProperties": false,
                                                "description": "Contains the paths to read in the data. The exact schema of this object depends on the content of `value.type`",
                                                "oneOf": [
                                                    {
                                                        "name": "AmountValue",
                                                        "required": [
                                                            "quantity",
                                                            "token"
                                                        ]
                                                    },
                                                    {
                                                        "name": "AddressValue",
                                                        "required": [
                                                            "address"
                                                        ]
                                                    },
                                                    {
                                                        "name": "NumberValue",
                                                        "required": [
                                                            "uint256"
                                                        ]
                                                    }
                                                ],
                                                "properties": {
                                                    "address": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "quantity": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "token": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "uint256": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    }
                                                },
                                                "type": "object"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "functionName": {
                                    "description": "Name displayed on the device to allow the user to identify the function called.",
                                    "type": "string"
                                },
                                "functionType": {
                                    "enum": [
                                        "stake",
                                        "swap",
                                        "wrap",
                                        "unwrap",
                                        "borrow",
                                        "repay",
                                        "supply",
                                        "withdraw",
                                        "claim_reward",
                                        "configure"
                                    ]
                                },
                                "options": {
                                    "description": "TBD",
                                    "type": "object"
                                },
                                "screen": {
                                    "description": "Optional description (per selector) of the screen displayed on PSD, overriding the default screen",
                                    "items": {
                                        "properties": {
                                            "label": {
                                                "description": "Label displayed on the device to allow the user to identify the argument.",
                                                "type": "string"
                                            },
                                            "name": {
                                                "description": "Name of the arguments, should match one existing arg from arguments.",
                                                "type": "string"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "selector": {
                                    "description": "Unique identifier of the function in the contract.",
                                    "pattern": "^0x[a-f0-9]{8}$",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "functionType",
                                "functionName",
                                "options",
                                "selector",
                                "arguments"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "required": [
                "name",
                "address",
                "parsers"
            ],
            "type": "array"
        },
        "name": {
            "pattern": "^[a-z]+$",
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "chainId",
        "contracts",
        "name"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/poap/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x0bb4d3e88243f4a057db77341e6916b0e449b158",
            "contractName": "PoapBridge",
            "selectors": {
                "0xaf68b302": {
                    "erc20OfInterest": [],
                    "method": "mintToken",
                    "plugin": "POAP"
                }
            }
        }
    ],
    "name": "Poap"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/kelp/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x036676389e48133b63a802f8635ad39e752d375d",
            "contractName": "LRTDepositPool",
            "selectors": {
                "0x72c51c0b": {
                    "erc20OfInterest": [],
                    "method": "depositETH",
                    "plugin": "Kelp"
                },
                "0xc3ae1766": {
                    "erc20OfInterest": [],
                    "method": "depositAsset",
                    "plugin": "Kelp"
                }
            }
        },
        {
            "address": "0x62de59c08eb5dae4b7e6f7a8cad3006d6965ec16",
            "contractName": "LRTWithdrawalManager",
            "selectors": {
                "0xc5a67b01": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdrawal",
                    "plugin": "Kelp"
                },
                "0xd3a86833": {
                    "erc20OfInterest": [],
                    "method": "completeWithdrawal",
                    "plugin": "Kelp"
                }
            }
        },
        {
            "address": "0xbf28c9fcb12a97441488f9c68faa49811a98688a",
            "contractName": "rsETHAdapter",
            "selectors": {
                "0x4e3c04bd": {
                    "erc20OfInterest": [],
                    "method": "getRSETHWithETH",
                    "plugin": "Kelp"
                },
                "0xb8aa0db9": {
                    "erc20OfInterest": [],
                    "method": "depositRsETH",
                    "plugin": "Kelp"
                },
                "0xe8c3516b": {
                    "erc20OfInterest": [],
                    "method": "getRSETHWithERC20",
                    "plugin": "Kelp"
                }
            }
        },
        {
            "address": "0xe1b4d34e8754600962cd944b535180bd758e6c2e",
            "contractName": "agETHToken",
            "selectors": {
                "0x7d41c86e": {
                    "erc20OfInterest": [],
                    "method": "requestRedeem",
                    "plugin": "Kelp"
                }
            }
        }
    ],
    "name": "Kelp"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/rocketpool/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xdd3f50f8a6cafbe9b31a427582963f465e745af8",
            "contractName": "RocketDepositPool",
            "selectors": {
                "0xd0e30db0": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Rocket Pool"
                }
            }
        },
        {
            "address": "0x1d8f8f00cfa6758d7be78336684788fb0ee0fa46",
            "contractName": "RocketStorage",
            "selectors": {
                "0xa543ccea": {
                    "erc20OfInterest": [],
                    "method": "setWithdrawalAddress",
                    "plugin": "Rocket Pool"
                },
                "0xbd439126": {
                    "erc20OfInterest": [],
                    "method": "confirmWithdrawalAddress",
                    "plugin": "Rocket Pool"
                }
            }
        },
        {
            "address": "0x0d8d8f8541b12a0e1194b7cc4b6d954b90ab82ec",
            "contractName": "RocketNodeStaking",
            "selectors": {
                "0x3e200d4b": {
                    "erc20OfInterest": [],
                    "method": "stakeRPL",
                    "plugin": "Rocket Pool"
                },
                "0x6b088d5c": {
                    "erc20OfInterest": [],
                    "method": "withdrawRPL",
                    "plugin": "Rocket Pool"
                },
                "0xcb1c8321": {
                    "erc20OfInterest": [],
                    "method": "stakeRPLFor",
                    "plugin": "Rocket Pool"
                }
            }
        },
        {
            "address": "0xae78736cd615f374d3085123a210448e74fc6393",
            "contractName": "RocketTokenRETH",
            "selectors": {
                "0x42966c68": {
                    "erc20OfInterest": [],
                    "method": "burn",
                    "plugin": "Rocket Pool"
                }
            }
        },
        {
            "address": "0xd33526068d116ce69f19a9ee46f0bd304f21a51f",
            "contractName": "RocketTokenRPL",
            "selectors": {
                "0xfe784eaa": {
                    "erc20OfInterest": [],
                    "method": "swapTokens",
                    "plugin": "Rocket Pool"
                }
            }
        },
        {
            "address": "0x16d5a408e807db8ef7c578279beeee6b228f1c1c",
            "contractName": "RocketSwapRouter",
            "selectors": {
                "0x55362f4d": {
                    "erc20OfInterest": [],
                    "method": "swapTo",
                    "plugin": "Rocket Pool"
                },
                "0xa824ae8b": {
                    "erc20OfInterest": [],
                    "method": "swapFrom",
                    "plugin": "Rocket Pool"
                }
            }
        }
    ],
    "name": "Rocket Pool"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/[ L ] Market/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x33c6eec1723b12c46732f7ab41398de45641fa42",
            "contractName": "[ L ] Market",
            "selectors": {
                "0x1249c58b": {
                    "erc20OfInterest": [],
                    "method": "mint",
                    "plugin": "[ L ] Market"
                },
                "0xc111fb91": {
                    "erc20OfInterest": [],
                    "method": "preSaleMint",
                    "plugin": "[ L ] Market"
                }
            }
        },
        {
            "address": "0x880ed873dde83f533564903c8aebb6e9fa9f8c81",
            "contractName": "BrickNFT",
            "selectors": {
                "0x827481ea": {
                    "erc20OfInterest": [],
                    "method": "preSaleMint",
                    "plugin": "[ L ] Market"
                },
                "0xa0712d68": {
                    "erc20OfInterest": [],
                    "method": "mint",
                    "plugin": "[ L ] Market"
                }
            }
        },
        {
            "address": "0x20ecda43fdd84290c50dec35fe03b35f9bf2c6dc",
            "contractName": "[ Ledger ] Market â€“ Deadfellaz Nano X",
            "selectors": {
                "0x827481ea": {
                    "erc20OfInterest": [],
                    "method": "preSaleMint",
                    "plugin": "[ L ] Market"
                },
                "0xa0712d68": {
                    "erc20OfInterest": [],
                    "method": "mint",
                    "plugin": "[ L ] Market"
                }
            }
        },
        {
            "address": "0xd3214ef2ae5327468521be8d567e587b38e8ad79",
            "contractName": "Ledger Stax",
            "selectors": {
                "0x827481ea": {
                    "erc20OfInterest": [],
                    "method": "preSaleMint",
                    "plugin": "[ L ] Market"
                },
                "0xa0712d68": {
                    "erc20OfInterest": [],
                    "method": "mint",
                    "plugin": "[ L ] Market"
                }
            }
        },
        {
            "address": "0xb7cd561bcfa998700eba50b18f765bb92553426f",
            "contractName": "Forgotten Runes",
            "selectors": {
                "0x827481ea": {
                    "erc20OfInterest": [],
                    "method": "preSaleMint",
                    "plugin": "[ L ] Market"
                },
                "0xa0712d68": {
                    "erc20OfInterest": [],
                    "method": "mint",
                    "plugin": "[ L ] Market"
                }
            }
        }
    ],
    "name": "[ L ] Market"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/midas/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x99361435420711723aF805F08187c9E6bF796683",
            "contractName": "MTbillDepositVault",
            "selectors": {
                "0xc02dd27a": {
                    "erc20OfInterest": [],
                    "method": "depositInstant",
                    "plugin": "Midas"
                },
                "0x6e26b9f8": {
                    "erc20OfInterest": [],
                    "method": "depositRequest",
                    "plugin": "Midas"
                }
            }
        },
        {
            "address": "0xa8a5c4FF4c86a459EBbDC39c5BE77833B3A15d88",
            "contractName": "MBasisDepositVault",
            "selectors": {
                "0xc02dd27a": {
                    "erc20OfInterest": [],
                    "method": "depositInstant",
                    "plugin": "Midas"
                },
                "0x6e26b9f8": {
                    "erc20OfInterest": [],
                    "method": "depositRequest",
                    "plugin": "Midas"
                }
            }
        },
        {
            "address": "0xF6e51d24F4793Ac5e71e0502213a9BBE3A6d4517",
            "contractName": "MTbillRedemptionVault",
            "selectors": {
                "0x8b53f75e": {
                    "erc20OfInterest": [],
                    "method": "redeemInstant",
                    "plugin": "Midas"
                },
                "0xbfc2d46a": {
                    "erc20OfInterest": [],
                    "method": "redeemRequest",
                    "plugin": "Midas"
                },
                "0xd5f73f5c": {
                    "erc20OfInterest": [],
                    "method": "redeemFiatRequest",
                    "plugin": "Midas"
                }
            }
        },
        {
            "address": "0x19AB19e61A930bc5C7B75Bf06cDd954218Ca9F0b",
            "contractName": "MBasisRedemptionVault",
            "selectors": {
                "0x8b53f75e": {
                    "erc20OfInterest": [],
                    "method": "redeemInstant",
                    "plugin": "Midas"
                },
                "0xbfc2d46a": {
                    "erc20OfInterest": [],
                    "method": "redeemRequest",
                    "plugin": "Midas"
                },
                "0xd5f73f5c": {
                    "erc20OfInterest": [],
                    "method": "redeemFiatRequest",
                    "plugin": "Midas"
                }
            }
        },
        {
            "address": "0x569D7dccBF6923350521ecBC28A555A500c4f0Ec",
            "contractName": "MTbillRedemptionVaultBuidl",
            "selectors": {
                "0x8b53f75e": {
                    "erc20OfInterest": [],
                    "method": "redeemInstant",
                    "plugin": "Midas"
                },
                "0xbfc2d46a": {
                    "erc20OfInterest": [],
                    "method": "redeemRequest",
                    "plugin": "Midas"
                },
                "0xd5f73f5c": {
                    "erc20OfInterest": [],
                    "method": "redeemFiatRequest",
                    "plugin": "Midas"
                }
            }
        },
        {
            "address": "0x0D89C1C4799353F3805A3E6C4e1Cbbb83217D123",
            "contractName": "MBasisRedemptionVaultSwapper",
            "selectors": {
                "0x8b53f75e": {
                    "erc20OfInterest": [],
                    "method": "redeemInstant",
                    "plugin": "Midas"
                },
                "0xbfc2d46a": {
                    "erc20OfInterest": [],
                    "method": "redeemRequest",
                    "plugin": "Midas"
                },
                "0xd5f73f5c": {
                    "erc20OfInterest": [],
                    "method": "redeemFiatRequest",
                    "plugin": "Midas"
                }
            }
        }
    ],
    "name": "Midas"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/rarible/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x9757f2d2b135150bbeb65308d4a91804107cd8d6",
            "contractName": "RaribleContract",
            "selectors": {
                "0xe2864fe3": {
                    "erc20OfInterest": [],
                    "method": "cancel",
                    "plugin": "Rarible"
                },
                "0xe99a3f80": {
                    "erc20OfInterest": [],
                    "method": "matchOrders",
                    "plugin": "Rarible"
                }
            }
        },
        {
            "address": "0x6e42262978de5233c8d5b05b128c121fba110da4",
            "contractName": "RaribleContract",
            "selectors": {
                "0x27050d1f": {
                    "erc20OfInterest": [],
                    "method": "createToken",
                    "plugin": "Rarible"
                }
            }
        },
        {
            "address": "0xf6793da657495ffeff9ee6350824910abc21356c",
            "contractName": "RaribleContract",
            "selectors": {
                "0x22a775b6": {
                    "erc20OfInterest": [],
                    "method": "mintAndTransfer",
                    "plugin": "Rarible"
                },
                "0x3db397c6": {
                    "erc20OfInterest": [],
                    "method": "__ERC721Rarible_init",
                    "plugin": "Rarible"
                },
                "0x832fbb29": {
                    "erc20OfInterest": [],
                    "method": "transferFromOrMint",
                    "plugin": "Rarible"
                },
                "0xa22cb465": {
                    "erc20OfInterest": [],
                    "method": "setApprovalForAll",
                    "plugin": "Rarible"
                }
            }
        },
        {
            "address": "0xc9154424b823b10579895ccbe442d41b9abd96ed",
            "contractName": "RaribleContract",
            "selectors": {
                "0x22a775b6": {
                    "erc20OfInterest": [],
                    "method": "mintAndTransfer",
                    "plugin": "Rarible"
                },
                "0x3db397c6": {
                    "erc20OfInterest": [],
                    "method": "__ERC721Rarible_init",
                    "plugin": "Rarible"
                },
                "0x832fbb29": {
                    "erc20OfInterest": [],
                    "method": "transferFromOrMint",
                    "plugin": "Rarible"
                },
                "0xa22cb465": {
                    "erc20OfInterest": [],
                    "method": "setApprovalForAll",
                    "plugin": "Rarible"
                }
            }
        }
    ],
    "name": "Rarible"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/alkemi/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x397c315d64d74d82a731d656f9c4d586d200f90a",
            "contractName": "AlkemiEarn",
            "selectors": {
                "0x4b8a3529": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "borrow",
                    "plugin": "Alkemi"
                },
                "0xabdb5ea8": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "repayBorrow",
                    "plugin": "Alkemi"
                },
                "0xe61604cf": {
                    "erc20OfInterest": [
                        "assetBorrow",
                        "assetCollateral"
                    ],
                    "method": "liquidateBorrow",
                    "plugin": "Alkemi"
                },
                "0xf2b9fdb8": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "supply",
                    "plugin": "Alkemi"
                },
                "0xf3fef3a3": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "withdraw",
                    "plugin": "Alkemi"
                }
            }
        },
        {
            "address": "0x4822d9172e5b76b9db37b75f5552f9988f98a888",
            "contractName": "AlkemiEarnOpen",
            "selectors": {
                "0x4b8a3529": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "borrow",
                    "plugin": "Alkemi"
                },
                "0xabdb5ea8": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "repayBorrow",
                    "plugin": "Alkemi"
                },
                "0xe61604cf": {
                    "erc20OfInterest": [
                        "assetBorrow",
                        "assetCollateral"
                    ],
                    "method": "liquidateBorrow",
                    "plugin": "Alkemi"
                },
                "0xf2b9fdb8": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "supply",
                    "plugin": "Alkemi"
                },
                "0xf3fef3a3": {
                    "erc20OfInterest": [
                        "asset"
                    ],
                    "method": "withdraw",
                    "plugin": "Alkemi"
                }
            }
        },
        {
            "address": "0x14716c982fd8b7f1e8f0b4dbb496dce438a29d93",
            "contractName": "AlkemiDao",
            "selectors": {
                "0x71d6e892": {
                    "erc20OfInterest": [],
                    "method": "claimAlk",
                    "plugin": "Alkemi"
                }
            }
        }
    ],
    "name": "Alkemi"
}
