=== LedgerHQ/ledger-asset-dapps/ethereum/parsers.schema.json
{
    "$defs": {
        "argumentValue": {
            "additionalProperties": false,
            "properties": {
                "constant": {
                    "description": "A constant value, independant of the contract data to parse. Can be used to handle implicit tokens definitions.",
                    "type": "string"
                },
                "oneOf": [
                    {
                        "required": [
                            "path"
                        ]
                    },
                    {
                        "required": [
                            "constant"
                        ]
                    }
                ],
                "path": {
                    "additionalProperties": false,
                    "anyOf": [
                        {
                            "required": [
                                "default"
                            ]
                        },
                        {
                            "required": [
                                "transaction"
                            ]
                        },
                        {
                            "required": [
                                "default",
                                "transaction"
                            ]
                        }
                    ],
                    "description": "Defines the paths to use to extract the argument's value, either in the contract data or in the transaction data.",
                    "properties": {
                        "default": {
                            "type": "string"
                        },
                        "transaction": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "description": "Description of a DApp and all the contracts linked to it.",
    "properties": {
        "blockchainName": {
            "enum": [
                "ethereum"
            ]
        },
        "chainId": {
            "enum": [
                1
            ]
        },
        "contracts": {
            "additionalProperties": false,
            "description": "The different contracts linked to the over-arching DApp.",
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-fA-F0-9]{40}$",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "parsers": {
                        "description": "Description of contract's functions along with the arguments we want to parse and validate.",
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "arguments": {
                                    "description": "Arguments that we want to display on the device for user validation.",
                                    "items": {
                                        "properties": {
                                            "format": {
                                                "description": "The format (different from the type) describes how the parsed argument should be displayed on the device.",
                                                "enum": [
                                                    "amount",
                                                    "ascii",
                                                    "boolean",
                                                    "eip55",
                                                    "percentage",
                                                    "raw"
                                                ]
                                            },
                                            "name": {
                                                "description": "Internal name of the argument, can be different from the name in the ABI.",
                                                "type": "string"
                                            },
                                            "value": {
                                                "additionalProperties": false,
                                                "description": "Contains the paths to read in the data. The exact schema of this object depends on the content of `value.type`",
                                                "oneOf": [
                                                    {
                                                        "name": "AmountValue",
                                                        "required": [
                                                            "quantity",
                                                            "token"
                                                        ]
                                                    },
                                                    {
                                                        "name": "AddressValue",
                                                        "required": [
                                                            "address"
                                                        ]
                                                    },
                                                    {
                                                        "name": "NumberValue",
                                                        "required": [
                                                            "uint256"
                                                        ]
                                                    }
                                                ],
                                                "properties": {
                                                    "address": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "quantity": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "token": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "uint256": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    }
                                                },
                                                "type": "object"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "functionName": {
                                    "description": "Name displayed on the device to allow the user to identify the function called.",
                                    "type": "string"
                                },
                                "functionType": {
                                    "enum": [
                                        "stake",
                                        "swap",
                                        "wrap",
                                        "unwrap",
                                        "borrow",
                                        "repay",
                                        "supply",
                                        "withdraw",
                                        "claim_reward",
                                        "configure"
                                    ]
                                },
                                "options": {
                                    "description": "TBD",
                                    "type": "object"
                                },
                                "screen": {
                                    "description": "Optional description (per selector) of the screen displayed on PSD, overriding the default screen",
                                    "items": {
                                        "properties": {
                                            "label": {
                                                "description": "Label displayed on the device to allow the user to identify the argument.",
                                                "type": "string"
                                            },
                                            "name": {
                                                "description": "Name of the arguments, should match one existing arg from arguments.",
                                                "type": "string"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "selector": {
                                    "description": "Unique identifier of the function in the contract.",
                                    "pattern": "^0x[a-f0-9]{8}$",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "functionType",
                                "functionName",
                                "options",
                                "selector",
                                "arguments"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "required": [
                "name",
                "address",
                "parsers"
            ],
            "type": "array"
        },
        "name": {
            "pattern": "^[a-z]+$",
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "chainId",
        "contracts",
        "name"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/stakedao/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xa2761b0539374eb7af2155f76eb09864af075250",
            "contractName": "PassiveETH",
            "selectors": {
                "0x2e1a7d4d": {
                    "erc20OfInterest": [],
                    "method": "withdraw",
                    "plugin": "StakeDAO"
                },
                "0xb6b55f25": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "StakeDAO"
                },
                "0xde5f6268": {
                    "erc20OfInterest": [],
                    "method": "depositAll",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0x9b8f14554f40705de7908879e2228d2ac94fde1a",
            "contractName": "ETHCallOpt",
            "selectors": {
                "0x5358fbda": {
                    "erc20OfInterest": [],
                    "method": "depositETH",
                    "plugin": "StakeDAO"
                },
                "0xc7cdea37": {
                    "erc20OfInterest": [],
                    "method": "withdrawETH",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0x227e4635c5fe22d1e36dab1c921b62f8acc451b9",
            "contractName": "BTCCallOpt",
            "selectors": {
                "0x4d5693ab": {
                    "erc20OfInterest": [],
                    "method": "depositUnderlying",
                    "plugin": "StakeDAO"
                },
                "0xc22fb4ef": {
                    "erc20OfInterest": [],
                    "method": "withdrawUnderlying",
                    "plugin": "StakeDAO"
                },
                "0xcc8690ac": {
                    "erc20OfInterest": [],
                    "method": "depositCrvLp",
                    "plugin": "StakeDAO"
                },
                "0xecfe0521": {
                    "erc20OfInterest": [],
                    "method": "withdrawCrvLp",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0xfea5e213bbd81a8a94d0e1edb09dbd7ceab61e1c",
            "contractName": "Masterchef",
            "selectors": {
                "0x441a3e70": {
                    "erc20OfInterest": [],
                    "method": "withdraw",
                    "plugin": "StakeDAO"
                },
                "0xe2bbb158": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0x20d1b558ef44a6e23d9bf4bf8db1653626e642c3",
            "contractName": "Premium",
            "selectors": {
                "0x2e1a7d4d": {
                    "erc20OfInterest": [],
                    "method": "withdraw",
                    "plugin": "StakeDAO"
                },
                "0x3d18b912": {
                    "erc20OfInterest": [],
                    "method": "getReward",
                    "plugin": "StakeDAO"
                },
                "0x7b0472f0": {
                    "erc20OfInterest": [],
                    "method": "stake",
                    "plugin": "StakeDAO"
                },
                "0xe9fad8ee": {
                    "erc20OfInterest": [],
                    "method": "exit",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0xac14864ce5a98af3248ffbf549441b04421247d3",
            "contractName": "Sanctuary",
            "selectors": {
                "0x67dfd4c9": {
                    "erc20OfInterest": [],
                    "method": "leave",
                    "plugin": "StakeDAO"
                },
                "0xa59f3e0c": {
                    "erc20OfInterest": [],
                    "method": "enter",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0x221738f73fa4bfca91918e77d112b87d918c751f",
            "contractName": "Palace",
            "selectors": {
                "0x2e1a7d4d": {
                    "erc20OfInterest": [],
                    "method": "withdraw",
                    "plugin": "StakeDAO"
                },
                "0xa694fc3a": {
                    "erc20OfInterest": [],
                    "method": "stake",
                    "plugin": "StakeDAO"
                }
            }
        },
        {
            "address": "0xa324a2e3a6f64bd588565e0e1e2dd50e7a68bdd9",
            "contractName": "NFtBoost",
            "selectors": {
                "0x2def6620": {
                    "erc20OfInterest": [],
                    "method": "unstake",
                    "plugin": "StakeDAO"
                },
                "0xa694fc3a": {
                    "erc20OfInterest": [],
                    "method": "stake",
                    "plugin": "StakeDAO"
                }
            }
        }
    ],
    "name": "StakeDAO"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/stader/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xf03a7eb46d01d9ecaa104558c732cf82f6b6b645",
            "contractName": "MaticX",
            "selectors": {
                "0x745400c9": {
                    "erc20OfInterest": [],
                    "method": "requestWithdraw",
                    "plugin": "Staderlabs"
                },
                "0xea99c2a6": {
                    "erc20OfInterest": [],
                    "method": "submit",
                    "plugin": "Staderlabs"
                },
                "0xf8444436": {
                    "erc20OfInterest": [],
                    "method": "claimWithdrawal",
                    "plugin": "Staderlabs"
                }
            }
        },
        {
            "address": "0xcf5ea1b38380f6af39068375516daf40ed70d299",
            "contractName": "StaderStakePoolsManager",
            "selectors": {
                "0xb7482509": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Staderlabs"
                }
            }
        },
        {
            "address": "0x9f0491b32dbce587c50c4c43ab303b06478193a7",
            "contractName": "UserWithdrawalManager",
            "selectors": {
                "0x1f7ec122": {
                    "erc20OfInterest": [],
                    "method": "requestWithdraw",
                    "plugin": "Staderlabs"
                },
                "0x379607f5": {
                    "erc20OfInterest": [],
                    "method": "claim",
                    "plugin": "Staderlabs"
                }
            }
        }
    ],
    "name": "Staderlabs"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/permit/eip712.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
            "contractName": "USDC",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Owner",
                                "path": "owner"
                            },
                            {
                                "label": "Spender",
                                "path": "spender"
                            },
                            {
                                "label": "Allowance",
                                "path": "value"
                            },
                            {
                                "format": "datetime",
                                "label": "Deadline",
                                "path": "deadline"
                            }
                        ],
                        "label": "Permit"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            },
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            }
                        ],
                        "Permit": [
                            {
                                "name": "owner",
                                "type": "address"
                            },
                            {
                                "name": "spender",
                                "type": "address"
                            },
                            {
                                "name": "value",
                                "type": "uint256"
                            },
                            {
                                "name": "nonce",
                                "type": "uint256"
                            },
                            {
                                "name": "deadline",
                                "type": "uint256"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "Permit"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/1inch/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x11111112542d85b3ef69ae05771c2dccff4faa26",
            "contractName": "AggregationRouterV3",
            "selectors": {
                "0x2e95b6c8": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "unoswap",
                    "plugin": "1inch"
                },
                "0x7c025200": {
                    "erc20OfInterest": [
                        "desc.srcToken",
                        "desc.dstToken"
                    ],
                    "method": "swap",
                    "plugin": "1inch"
                }
            }
        },
        {
            "address": "0x1111111254fb6c44bac0bed2854e76f90643097d",
            "contractName": "AggregationRouterV4",
            "selectors": {
                "0x2521b930": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "uniswapV3SwapToWithPermit",
                    "plugin": "1inch"
                },
                "0x2e95b6c8": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "unoswap",
                    "plugin": "1inch"
                },
                "0x4cc4a27b": {
                    "erc20OfInterest": [],
                    "method": "fillOrderRFQToWithPermit",
                    "plugin": "1inch"
                },
                "0x7c025200": {
                    "erc20OfInterest": [
                        "desc.srcToken",
                        "desc.dstToken"
                    ],
                    "method": "swap",
                    "plugin": "1inch"
                },
                "0xa1251d75": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "unoswapWithPermit",
                    "plugin": "1inch"
                },
                "0xb0431182": {
                    "erc20OfInterest": [
                        "srcToken",
                        "dstToken"
                    ],
                    "method": "clipperSwap",
                    "plugin": "1inch"
                },
                "0xbc80f1a8": {
                    "erc20OfInterest": [],
                    "method": "uniswapV3SwapTo",
                    "plugin": "1inch"
                },
                "0xd0a3b665": {
                    "erc20OfInterest": [],
                    "method": "fillOrderRFQ",
                    "plugin": "1inch"
                },
                "0xd6a92a5d": {
                    "erc20OfInterest": [
                        "srcToken",
                        "dstToken"
                    ],
                    "method": "clipperSwapToWithPermit",
                    "plugin": "1inch"
                },
                "0xe449022e": {
                    "erc20OfInterest": [],
                    "method": "uniswapV3Swap",
                    "plugin": "1inch"
                }
            }
        },
        {
            "address": "0x1111111254eeb25477b68fb85ed929f73a960582",
            "contractName": "AggregationRouterV5",
            "selectors": {
                "0x0502b1c5": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "unoswap",
                    "plugin": "1inch"
                },
                "0x12aa3caf": {
                    "erc20OfInterest": [
                        "desc.srcToken",
                        "desc.dstToken"
                    ],
                    "method": "swap",
                    "plugin": "1inch"
                },
                "0x3c15fd91": {
                    "erc20OfInterest": [
                        "srcToken"
                    ],
                    "method": "unoswapToWithPermit",
                    "plugin": "1inch"
                },
                "0x3eca9c0a": {
                    "erc20OfInterest": [
                        "order.makerAsset",
                        "order.takerAsset"
                    ],
                    "method": "fillOrderRFQ",
                    "plugin": "1inch"
                },
                "0x70ccbd31": {
                    "erc20OfInterest": [
                        "order.makerAsset",
                        "order.takerAsset"
                    ],
                    "method": "fillOrderRFQToWithPermit",
                    "plugin": "1inch"
                },
                "0x84bd6d29": {
                    "erc20OfInterest": [
                        "srcToken",
                        "dstToken"
                    ],
                    "method": "clipperSwap",
                    "plugin": "1inch"
                },
                "0xc805a666": {
                    "erc20OfInterest": [
                        "srcToken",
                        "dstToken"
                    ],
                    "method": "clipperSwapToWithPermit",
                    "plugin": "1inch"
                }
            }
        }
    ],
    "name": "1inch"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/figment/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xf0075b3cf8953d3e23b0ef65960913fd97eb5227",
            "contractName": "FigmentEth2Depositor",
            "selectors": {
                "0x4f498c73": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Figment"
                }
            }
        }
    ],
    "name": "Figment"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/eigenlayer/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x858646372cc42e1a627fce94aa7a7033e7cf075a",
            "contractName": "EigenLayerStrategyManager",
            "selectors": {
                "0xe7a050aa": {
                    "erc20OfInterest": [],
                    "method": "depositIntoStrategy",
                    "plugin": "EigenLayer"
                }
            }
        },
        {
            "address": "0x39053d51b77dc0d36036fc1fcc8cb819df8ef37a",
            "contractName": "EigenLayerDelegationManager",
            "selectors": {
                "0x0dd8dd02": {
                    "erc20OfInterest": [],
                    "method": "queueWithdrawals",
                    "plugin": "EigenLayer"
                },
                "0x33404396": {
                    "erc20OfInterest": [],
                    "method": "completeQueuedWithdrawals",
                    "plugin": "EigenLayer"
                },
                "0xda8be864": {
                    "erc20OfInterest": [],
                    "method": "undelegate",
                    "plugin": "EigenLayer"
                },
                "0xeea9064b": {
                    "erc20OfInterest": [],
                    "method": "delegateTo",
                    "plugin": "EigenLayer"
                }
            }
        }
    ],
    "name": "EigenLayer"
}
