=== LedgerHQ/ledger-asset-dapps/ethereum/parsers.schema.json
{
    "$defs": {
        "argumentValue": {
            "additionalProperties": false,
            "properties": {
                "constant": {
                    "description": "A constant value, independant of the contract data to parse. Can be used to handle implicit tokens definitions.",
                    "type": "string"
                },
                "oneOf": [
                    {
                        "required": [
                            "path"
                        ]
                    },
                    {
                        "required": [
                            "constant"
                        ]
                    }
                ],
                "path": {
                    "additionalProperties": false,
                    "anyOf": [
                        {
                            "required": [
                                "default"
                            ]
                        },
                        {
                            "required": [
                                "transaction"
                            ]
                        },
                        {
                            "required": [
                                "default",
                                "transaction"
                            ]
                        }
                    ],
                    "description": "Defines the paths to use to extract the argument's value, either in the contract data or in the transaction data.",
                    "properties": {
                        "default": {
                            "type": "string"
                        },
                        "transaction": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "description": "Description of a DApp and all the contracts linked to it.",
    "properties": {
        "blockchainName": {
            "enum": [
                "ethereum"
            ]
        },
        "chainId": {
            "enum": [
                1
            ]
        },
        "contracts": {
            "additionalProperties": false,
            "description": "The different contracts linked to the over-arching DApp.",
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-fA-F0-9]{40}$",
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "parsers": {
                        "description": "Description of contract's functions along with the arguments we want to parse and validate.",
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "arguments": {
                                    "description": "Arguments that we want to display on the device for user validation.",
                                    "items": {
                                        "properties": {
                                            "format": {
                                                "description": "The format (different from the type) describes how the parsed argument should be displayed on the device.",
                                                "enum": [
                                                    "amount",
                                                    "ascii",
                                                    "boolean",
                                                    "eip55",
                                                    "percentage",
                                                    "raw"
                                                ]
                                            },
                                            "name": {
                                                "description": "Internal name of the argument, can be different from the name in the ABI.",
                                                "type": "string"
                                            },
                                            "value": {
                                                "additionalProperties": false,
                                                "description": "Contains the paths to read in the data. The exact schema of this object depends on the content of `value.type`",
                                                "oneOf": [
                                                    {
                                                        "name": "AmountValue",
                                                        "required": [
                                                            "quantity",
                                                            "token"
                                                        ]
                                                    },
                                                    {
                                                        "name": "AddressValue",
                                                        "required": [
                                                            "address"
                                                        ]
                                                    },
                                                    {
                                                        "name": "NumberValue",
                                                        "required": [
                                                            "uint256"
                                                        ]
                                                    }
                                                ],
                                                "properties": {
                                                    "address": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "quantity": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "token": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    },
                                                    "uint256": {
                                                        "$ref": "#/$defs/argumentValue"
                                                    }
                                                },
                                                "type": "object"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "functionName": {
                                    "description": "Name displayed on the device to allow the user to identify the function called.",
                                    "type": "string"
                                },
                                "functionType": {
                                    "enum": [
                                        "stake",
                                        "swap",
                                        "wrap",
                                        "unwrap",
                                        "borrow",
                                        "repay",
                                        "supply",
                                        "withdraw",
                                        "claim_reward",
                                        "configure"
                                    ]
                                },
                                "options": {
                                    "description": "TBD",
                                    "type": "object"
                                },
                                "screen": {
                                    "description": "Optional description (per selector) of the screen displayed on PSD, overriding the default screen",
                                    "items": {
                                        "properties": {
                                            "label": {
                                                "description": "Label displayed on the device to allow the user to identify the argument.",
                                                "type": "string"
                                            },
                                            "name": {
                                                "description": "Name of the arguments, should match one existing arg from arguments.",
                                                "type": "string"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "selector": {
                                    "description": "Unique identifier of the function in the contract.",
                                    "pattern": "^0x[a-f0-9]{8}$",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "functionType",
                                "functionName",
                                "options",
                                "selector",
                                "arguments"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "type": "object"
            },
            "required": [
                "name",
                "address",
                "parsers"
            ],
            "type": "array"
        },
        "name": {
            "pattern": "^[a-z]+$",
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "chainId",
        "contracts",
        "name"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/opensea/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x7be8076f4ea4a4ad08075c2508e481d6c946d12b",
            "contractName": "OpenSea",
            "selectors": {
                "0xa8a41c70": {
                    "erc20OfInterest": [
                        "addrs.6",
                        "addrs.4"
                    ],
                    "method": "cancelOrder_",
                    "plugin": "OpenSea"
                },
                "0xab834bab": {
                    "erc20OfInterest": [
                        "addrs.6",
                        "addrs.4"
                    ],
                    "method": "atomicMatch_",
                    "plugin": "OpenSea"
                }
            }
        },
        {
            "address": "0x7f268357a8c2552623316e2562d90e642bb538e5",
            "contractName": "OpenSea",
            "selectors": {
                "0xa8a41c70": {
                    "erc20OfInterest": [
                        "addrs.6",
                        "addrs.4"
                    ],
                    "method": "cancelOrder_",
                    "plugin": "OpenSea"
                },
                "0xab834bab": {
                    "erc20OfInterest": [
                        "addrs.6",
                        "addrs.4"
                    ],
                    "method": "atomicMatch_",
                    "plugin": "OpenSea"
                }
            }
        },
        {
            "address": "0xa5409ec958c83c3f309868babaca7c86dcb077c1",
            "contractName": "OpenSeaRegistry",
            "selectors": {
                "0xddd81f82": {
                    "erc20OfInterest": [],
                    "method": "registerProxy",
                    "plugin": "OpenSea"
                }
            }
        }
    ],
    "name": "OpenSea"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/ribbon/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xe63151a0ed4e5fafdc951d877102cf0977abd365",
            "contractName": "RibbonAaveThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xb6b55f25": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        },
        {
            "address": "0x65a833afdc250d9d38f8cd9bc2b1e3132db13b2f",
            "contractName": "RibbonWBTCThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xb6b55f25": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        },
        {
            "address": "0xc0cf10dd710aefb209d9dc67bc746510ffd98a53",
            "contractName": "RibbonAPEThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xb6b55f25": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        },
        {
            "address": "0xcc323557c71c0d1d20a1861dc69c06c5f3cc9624",
            "contractName": "RibbonETHPutThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xb6b55f25": {
                    "erc20OfInterest": [],
                    "method": "deposit",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        },
        {
            "address": "0x25751853eab4d0eb3652b5eb6ecb102a2789644b",
            "contractName": "RibbonETHThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xf6326fb3": {
                    "erc20OfInterest": [],
                    "method": "depositETH",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        },
        {
            "address": "0x53773e034d9784153471813dacaff53dbbb78e8c",
            "contractName": "RibbonSTETHThetaVault",
            "selectors": {
                "0x2775d01c": {
                    "erc20OfInterest": [],
                    "method": "withdrawInstantly",
                    "plugin": "Ribbon"
                },
                "0x31807e42": {
                    "erc20OfInterest": [],
                    "method": "depositYieldToken",
                    "plugin": "Ribbon"
                },
                "0x7e108d52": {
                    "erc20OfInterest": [],
                    "method": "initiateWithdraw",
                    "plugin": "Ribbon"
                },
                "0xf6326fb3": {
                    "erc20OfInterest": [],
                    "method": "depositETH",
                    "plugin": "Ribbon"
                },
                "0xf756fa21": {
                    "erc20OfInterest": [],
                    "method": "completeWithdraw",
                    "plugin": "Ribbon"
                }
            }
        }
    ],
    "name": "Ribbon"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/uniswap/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x3fc91a3afd70395cd496c647d5a6cc9d4b2b7fad",
            "contractName": "UniversalRouter",
            "selectors": {
                "0x3593564c": {
                    "erc20OfInterest": [],
                    "method": "execute",
                    "plugin": "Uniswap"
                }
            }
        },
        {
            "address": "0x66a9893cc07d91d95644aedd05d03f95e1dba8af",
            "contractName": "UniversalRouter",
            "selectors": {
                "0x3593564c": {
                    "erc20OfInterest": [],
                    "method": "execute",
                    "plugin": "Uniswap"
                }
            }
        }
    ],
    "name": "Uniswap"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/squid/b2c.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0xce16f69375520ab01377ce7b88f5ba8c48f8d666",
            "contractName": "SquidRouterProxy",
            "selectors": {
                "0x3c659741": {
                    "erc20OfInterest": [],
                    "method": "bridgeCall",
                    "plugin": "Squid"
                },
                "0x8ca3bf68": {
                    "erc20OfInterest": [
                        "token"
                    ],
                    "method": "callBridgeCall",
                    "plugin": "Squid"
                },
                "0xf35af1f8": {
                    "erc20OfInterest": [
                        "token"
                    ],
                    "method": "callBridge",
                    "plugin": "Squid"
                }
            }
        },
        {
            "address": "0x4f4495243837681061c4743b74b3eedf548d56a5",
            "contractName": "AxelarGatewayProxyMultisig",
            "selectors": {
                "0x26ef699d": {
                    "erc20OfInterest": [],
                    "method": "sendToken",
                    "plugin": "Squid"
                }
            }
        }
    ],
    "name": "Squid"
}

=== LedgerHQ/ledger-asset-dapps/ethereum/snapshot/eip712.schema.json
{
    "blockchainName": "ethereum",
    "chainId": 1,
    "contracts": [
        {
            "address": "0x0000000000000000000000000000000000000000",
            "contractName": "Snapshot Vote",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Vote from",
                                "path": "from"
                            },
                            {
                                "label": "The space",
                                "path": "space"
                            },
                            {
                                "label": "Vote timestamp",
                                "path": "timestamp"
                            },
                            {
                                "label": "The proposal",
                                "path": "proposal"
                            },
                            {
                                "label": "Your vote",
                                "path": "choice"
                            },
                            {
                                "label": "The Reason",
                                "path": "reason"
                            },
                            {
                                "label": "The App",
                                "path": "app"
                            },
                            {
                                "label": "The metadata",
                                "path": "metadata"
                            }
                        ],
                        "label": "Vote Details"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            }
                        ],
                        "Vote": [
                            {
                                "name": "from",
                                "type": "address"
                            },
                            {
                                "name": "space",
                                "type": "string"
                            },
                            {
                                "name": "timestamp",
                                "type": "uint64"
                            },
                            {
                                "name": "proposal",
                                "type": "string"
                            },
                            {
                                "name": "choice",
                                "type": "uint32"
                            },
                            {
                                "name": "reason",
                                "type": "string"
                            },
                            {
                                "name": "app",
                                "type": "string"
                            },
                            {
                                "name": "metadata",
                                "type": "string"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "Snapshot"
}
