=== LedgerHQ/ledger-asset-dapps/polygon/eip712.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "blockchainName": {
            "enum": [
                "polygon"
            ]
        },
        "chainId": {
            "enum": [
                137
            ]
        },
        "contracts": {
            "items": {
                "properties": {
                    "address": {
                        "pattern": "^0x[a-z0-9]{40}$",
                        "type": "string"
                    },
                    "contractName": {
                        "type": "string"
                    },
                    "messages": {
                        "items": {
                            "additionalProperties": false,
                            "properties": {
                                "mapper": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "fields": {
                                            "items": {
                                                "additionalProperties": false,
                                                "properties": {
                                                    "assetPath": {
                                                        "type": "string"
                                                    },
                                                    "format": {
                                                        "enum": [
                                                            "amount",
                                                            "raw",
                                                            "datetime"
                                                        ]
                                                    },
                                                    "label": {
                                                        "maxLength": 39,
                                                        "minLength": 1,
                                                        "type": "string"
                                                    },
                                                    "path": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "path",
                                                    "label"
                                                ],
                                                "type": "object"
                                            },
                                            "minItems": 1,
                                            "type": "array"
                                        },
                                        "label": {
                                            "maxLength": 39,
                                            "minLength": 1,
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "label",
                                        "fields"
                                    ],
                                    "type": "object"
                                },
                                "schema": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "schema",
                                "mapper"
                            ],
                            "type": "object"
                        },
                        "minItems": 1,
                        "type": "array"
                    }
                },
                "required": [
                    "address",
                    "contractName",
                    "messages"
                ],
                "type": "object"
            },
            "minItems": 1,
            "type": "array"
        },
        "name": {
            "type": "string"
        }
    },
    "required": [
        "blockchainName",
        "contracts",
        "name",
        "chainId"
    ],
    "type": "object"
}

=== LedgerHQ/ledger-asset-dapps/polygon/ledgerquest/eip712.json
{
    "blockchainName": "polygon",
    "chainId": 137,
    "contracts": [
        {
            "address": "0x33c6eec1723b12c46732f7ab41398de45641fa42",
            "contractName": "LedgerQuest",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Receiver",
                                "path": "receiver"
                            },
                            {
                                "label": "Quest Type",
                                "path": "categoryId"
                            },
                            {
                                "label": "Collection",
                                "path": "collectionId"
                            }
                        ],
                        "label": "Mint"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            },
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            }
                        ],
                        "mint": [
                            {
                                "name": "receiver",
                                "type": "address"
                            },
                            {
                                "name": "categoryId",
                                "type": "uint256"
                            },
                            {
                                "name": "collectionId",
                                "type": "uint256"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "LedgerQuest"
}

=== LedgerHQ/ledger-asset-dapps/polygon/permit/eip712.json
{
    "blockchainName": "polygon",
    "chainId": 137,
    "contracts": [
        {
            "address": "0x27f8d03b3a2196956ed754badc28d73be8830a6e",
            "contractName": "Aave Matic Market DAI",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Owner",
                                "path": "owner"
                            },
                            {
                                "label": "Spender",
                                "path": "spender"
                            },
                            {
                                "format": "amount",
                                "label": "Allowance",
                                "path": "value"
                            },
                            {
                                "format": "datetime",
                                "label": "Deadline",
                                "path": "deadline"
                            }
                        ],
                        "label": "Permit Aave Matic Market DAI transfers"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            },
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            }
                        ],
                        "Permit": [
                            {
                                "name": "owner",
                                "type": "address"
                            },
                            {
                                "name": "spender",
                                "type": "address"
                            },
                            {
                                "name": "value",
                                "type": "uint256"
                            },
                            {
                                "name": "nonce",
                                "type": "uint256"
                            },
                            {
                                "name": "deadline",
                                "type": "uint256"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "address": "0x28424507fefb6f7f8e9d3860f56504e4e5f5f390",
            "contractName": "Aave Matic Market WETH",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Owner",
                                "path": "owner"
                            },
                            {
                                "label": "Spender",
                                "path": "spender"
                            },
                            {
                                "format": "amount",
                                "label": "Allowance",
                                "path": "value"
                            },
                            {
                                "format": "datetime",
                                "label": "Deadline",
                                "path": "deadline"
                            }
                        ],
                        "label": "Permit Aave Matic Market WETH transfers"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            },
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            }
                        ],
                        "Permit": [
                            {
                                "name": "owner",
                                "type": "address"
                            },
                            {
                                "name": "spender",
                                "type": "address"
                            },
                            {
                                "name": "value",
                                "type": "uint256"
                            },
                            {
                                "name": "nonce",
                                "type": "uint256"
                            },
                            {
                                "name": "deadline",
                                "type": "uint256"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "Permit"
}

=== LedgerHQ/ledger-asset-dapps/polygon/dispatch.xyz/eip712.schema.json
{
    "blockchainName": "polygon",
    "chainId": 137,
    "contracts": [
        {
            "address": "0xDb46d1Dc155634FbC732f92E853b10B288AD5a1d",
            "contractName": "Lens Protocol Profiles",
            "messages": [
                {
                    "mapper": {
                        "fields": [
                            {
                                "label": "Profile Ids",
                                "path": "profileIds"
                            },
                            {
                                "label": "Data",
                                "path": "datas"
                            },
                            {
                                "label": "Nonce",
                                "path": "nonce"
                            },
                            {
                                "label": "Expiration Date",
                                "path": "deadline"
                            }
                        ],
                        "label": "Dispatch.xyz Follow Profile"
                    },
                    "schema": {
                        "EIP712Domain": [
                            {
                                "name": "chainId",
                                "type": "uint256"
                            },
                            {
                                "name": "name",
                                "type": "string"
                            },
                            {
                                "name": "verifyingContract",
                                "type": "address"
                            },
                            {
                                "name": "version",
                                "type": "string"
                            }
                        ],
                        "FollowWithSig": [
                            {
                                "name": "profileIds",
                                "type": "uint256[]"
                            },
                            {
                                "name": "datas",
                                "type": "bytes[]"
                            },
                            {
                                "name": "nonce",
                                "type": "uint256"
                            },
                            {
                                "name": "deadline",
                                "type": "uint256"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "name": "Dispatch.xyz"
}
